IncludeFile("sh_animtables.lua")
IncludeFile("sh_badges.lua")
IncludeFile("sh_hulls.lua")
IncludeFile("sh_teams.lua")

CharacterFlag.AddFolder("content/characterflags")
Chat.AddFolder("content/chatcommands")
Command.AddFolder("content/commands")
Item.AddFolder("content/items")
Template.AddFolder("content/templates")
